[package]
authors = ["James Gloudemans <james.gloudemans@gmail.com>"]
edition = "2018"
name = "hubbub"
version = "0.1.0"

[dependencies]
bytes = "^1"
dashmap = "^4"
hubbublib = {path = "./hubbublib"}
serde_json = "^1.0"
tokio = {version = "1", features = ["full"]}
